CuteNinja\MemoriaBundle\Entity\BaseEntity:
    type: mappedSuperclass
    fields:
        status:
            type: string
            columnDefinition: ENUM('active', 'inactive')
            scale: 0
            length: 25
            unique: false
            nullable: false
            precision: 0
        creation:
            type: datetime
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0