imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: bundles/jms_serializer.yml }
    - { resource: bundles/fos_rest.yml }
    - { resource: bundles/cute_ninja_memoria.yml }

parameters:
    locale: en
    jms_serializer.camel_case_naming_strategy.class: JMS\Serializer\Naming\IdenticalPropertyNamingStrategy

framework:
    #esi:             ~
    #translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['php']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        handler_id:  ~
        save_path:   %kernel.root_dir%/../var/sessions/%kernel.environment%
    fragments:       ~
    http_method_override: true
    assets: ~

doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver:         pdo_mysql
                server_version: "%database_server_version%"
                host:           "%database_host%"
                port:           "%database_port%"
                dbname:         "%database_name%"
                user:           "%database_user%"
                password:       "%database_password%"
                charset:        UTF8
                mapping_types:
                    enum: string
            mobiparade:
                driver:         pdo_mysql
                server_version: "%database_server_version%"
                host:           "%database_host%"
                port:           "%database_port%"
                dbname:         "%mobiparade_database_name%"
                user:           "%database_user%"
                password:       "%database_password%"
                charset:        UTF8
                mapping_types:
                    enum: string
            setup_misc:
                driver:         pdo_mysql
                server_version: "%database_server_version%"
                host:           "%database_host%"
                port:           "%database_port%"
                dbname:         "%setup_misc_database_name%"
                user:           "%database_user%"
                password:       "%database_password%"
                charset:        UTF8
                mapping_types:
                    enum: string

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        #auto_mapping: true
        default_entity_manager: default
        entity_managers:
            default:
                naming_strategy: doctrine.orm.naming_strategy.underscore
                connection: default
                mappings:
                    CampaignManagementBundle: ~
                    MobPartnerBOUserBundle: ~
                    GenericEntityBundle: ~

            fakemobiparade:
                naming_strategy: doctrine.orm.naming_strategy.underscore
                connection: mobiparade
                mappings:
                    MobPartnerBOUserBundle: ~
                    GenericEntityBundle: ~

            fakesetupmisc:
                naming_strategy: doctrine.orm.naming_strategy.underscore
                connection: setup_misc
                mappings:
                    MobPartnerBOUserBundle: ~
                    GenericEntityBundle: ~